# DO NOT CHANGE the "init" and "install" sections below

image:
  - Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

build_script:
  - set OLDPATH=%PATH%
  - rmdir /s /Q C:\OpenSSL-Win32 C:\OpenSSL-Win64
  - cd %APPVEYOR_BUILD_FOLDER%\ccode
  - git clone https://github.com/iambaim/taucs.git
  - cd taucs
  - sh download.sh
  - SET TAUCS_BUILD_DIR=%cd%
  - build_win.bat
  - SET LTAUCS_LOC=-L%cd%\lib\linux
  - cd ..
  - build_win.bat
  - cd ..
  - rmdir /s /Q ccode
  - set PATH=%OLDPATH%
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
